import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google"; // Corrected font imports
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { SessionProvider } from "@/context/Sessioncontext";
import HeaderWrapper from "@/components/layouts/HeaderWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <HeaderWrapper/> */}
      <body
        className={`${inter.variable} ${robotoMono.variable} `}
      >
        <SessionProvider>
          <ThemeProvider>
            <div className="size-full bg-background"></div>
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
