export interface AvailableCourse {
  id: string;
  code: string;
  name: string;
  description: string;
  instructor: string;
  instructorAvatar?: string;
  department: string;
  semester: string;
  credits: number;
  schedule: string;
  students: number;
  maxStudents: number;
  rating: number;
  reviews: number;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  tags: string[];
  thumbnail?: string;
  enrolled: boolean; // User has enrolled in this course
}

export const allAvailableCourses: AvailableCourse[] = [
  {
    id: 'KTPM101',
    code: 'KTPM101',
    name: 'Kỹ thuật phần mềm',
    description: 'Học các nguyên lý cơ bản về phát triển phần mềm, quy trình Agile, và quản lý dự án phần mềm.',
    instructor: 'TS. Nguyễn Văn A',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Công nghệ Phần mềm',
    semester: 'HK1 2024-2025',
    credits: 3,
    schedule: 'Thứ 2, 4 (7:00 - 9:30)',
    students: 45,
    maxStudents: 60,
    rating: 4.8,
    reviews: 156,
    level: 'Intermediate',
    tags: ['Software Engineering', 'Agile', 'Project Management'],
    enrolled: true,
  },
  {
    id: 'MATH201',
    code: 'MATH201',
    name: 'Toán rời rạc',
    description: 'Khám phá các khái niệm toán học cơ bản cho khoa học máy tính: tập hợp, logic, đồ thị.',
    instructor: 'PGS.TS. Trần Thị B',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Toán - Tin',
    semester: 'HK1 2024-2025',
    credits: 4,
    schedule: 'Thứ 3, 5 (13:00 - 15:30)',
    students: 38,
    maxStudents: 50,
    rating: 4.6,
    reviews: 128,
    level: 'Intermediate',
    tags: ['Mathematics', 'Discrete Math', 'Graph Theory'],
    enrolled: true,
  },
  {
    id: 'CS101',
    code: 'CS101',
    name: 'Nhập môn lập trình',
    description: 'Khóa học cơ bản về lập trình với Python. Phù hợp cho người mới bắt đầu.',
    instructor: 'ThS. Lê Văn C',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Công nghệ Thông tin',
    semester: 'HK1 2024-2025',
    credits: 3,
    schedule: 'Thứ 2, 4 (13:00 - 15:30)',
    students: 52,
    maxStudents: 60,
    rating: 4.9,
    reviews: 203,
    level: 'Beginner',
    tags: ['Programming', 'Python', 'Fundamentals'],
    enrolled: false,
  },
  {
    id: 'WEB301',
    code: 'WEB301',
    name: 'Phát triển Web nâng cao',
    description: 'Học React, Next.js, Node.js và các công nghệ web hiện đại để xây dựng ứng dụng web full-stack.',
    instructor: 'TS. Phạm Minh D',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Công nghệ Phần mềm',
    semester: 'HK1 2024-2025',
    credits: 4,
    schedule: 'Thứ 3, 5 (7:00 - 9:30)',
    students: 35,
    maxStudents: 45,
    rating: 4.7,
    reviews: 89,
    level: 'Advanced',
    tags: ['Web Development', 'React', 'Next.js', 'Full-stack'],
    enrolled: false,
  },
  {
    id: 'DB201',
    code: 'DB201',
    name: 'Cơ sở dữ liệu',
    description: 'Thiết kế và quản lý cơ sở dữ liệu quan hệ. SQL, normalization, và tối ưu hóa truy vấn.',
    instructor: 'PGS.TS. Hoàng Thị E',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Hệ thống Thông tin',
    semester: 'HK1 2024-2025',
    credits: 3,
    schedule: 'Thứ 4, 6 (13:00 - 15:30)',
    students: 41,
    maxStudents: 50,
    rating: 4.5,
    reviews: 112,
    level: 'Intermediate',
    tags: ['Database', 'SQL', 'Data Management'],
    enrolled: false,
  },
  {
    id: 'AI301',
    code: 'AI301',
    name: 'Trí tuệ nhân tạo',
    description: 'Khám phá các thuật toán AI, machine learning, và deep learning với TensorFlow và PyTorch.',
    instructor: 'TS. Đặng Văn F',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Khoa học Máy tính',
    semester: 'HK1 2024-2025',
    credits: 4,
    schedule: 'Thứ 2, 4 (15:45 - 18:15)',
    students: 28,
    maxStudents: 40,
    rating: 4.9,
    reviews: 95,
    level: 'Advanced',
    tags: ['AI', 'Machine Learning', 'Deep Learning'],
    enrolled: false,
  },
  {
    id: 'MOBILE201',
    code: 'MOBILE201',
    name: 'Lập trình di động',
    description: 'Phát triển ứng dụng di động đa nền tảng với React Native và Flutter.',
    instructor: 'ThS. Vũ Thị G',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Công nghệ Phần mềm',
    semester: 'HK1 2024-2025',
    credits: 3,
    schedule: 'Thứ 3, 5 (15:45 - 18:15)',
    students: 33,
    maxStudents: 45,
    rating: 4.6,
    reviews: 74,
    level: 'Intermediate',
    tags: ['Mobile Development', 'React Native', 'Flutter'],
    enrolled: false,
  },
  {
    id: 'SEC301',
    code: 'SEC301',
    name: 'An toàn thông tin',
    description: 'Bảo mật mạng, mã hóa, và các kỹ thuật phòng chống tấn công mạng.',
    instructor: 'TS. Ngô Văn H',
    instructorAvatar: '/user.jpg',
    department: 'Khoa An toàn Thông tin',
    semester: 'HK1 2024-2025',
    credits: 4,
    schedule: 'Thứ 4, 6 (7:00 - 9:30)',
    students: 25,
    maxStudents: 35,
    rating: 4.8,
    reviews: 67,
    level: 'Advanced',
    tags: ['Security', 'Cryptography', 'Network Security'],
    enrolled: false,
  },
  {
    id: 'ALGO201',
    code: 'ALGO201',
    name: 'Cấu trúc dữ liệu & Giải thuật',
    description: 'Các cấu trúc dữ liệu cơ bản và thuật toán quan trọng trong khoa học máy tính.',
    instructor: 'PGS.TS. Bùi Văn I',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Khoa học Máy tính',
    semester: 'HK1 2024-2025',
    credits: 4,
    schedule: 'Thứ 2, 4 (9:45 - 12:15)',
    students: 48,
    maxStudents: 55,
    rating: 4.7,
    reviews: 142,
    level: 'Intermediate',
    tags: ['Algorithms', 'Data Structures', 'Problem Solving'],
    enrolled: false,
  },
  {
    id: 'CLOUD301',
    code: 'CLOUD301',
    name: 'Điện toán đám mây',
    description: 'AWS, Azure, Google Cloud Platform và kiến trúc microservices.',
    instructor: 'TS. Trương Thị K',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Hệ thống Thông tin',
    semester: 'HK1 2024-2025',
    credits: 3,
    schedule: 'Thứ 3, 5 (9:45 - 12:15)',
    students: 22,
    maxStudents: 30,
    rating: 4.8,
    reviews: 58,
    level: 'Advanced',
    tags: ['Cloud Computing', 'AWS', 'Microservices'],
    enrolled: false,
  },
  {
    id: 'UI201',
    code: 'UI201',
    name: 'Thiết kế giao diện người dùng',
    description: 'UX/UI design principles, Figma, và tạo prototype cho ứng dụng.',
    instructor: 'ThS. Mai Văn L',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Công nghệ Phần mềm',
    semester: 'HK1 2024-2025',
    credits: 3,
    schedule: 'Thứ 4, 6 (15:45 - 18:15)',
    students: 31,
    maxStudents: 40,
    rating: 4.9,
    reviews: 88,
    level: 'Beginner',
    tags: ['UI/UX', 'Design', 'Figma', 'Prototyping'],
    enrolled: false,
  },
  {
    id: 'DEVOPS301',
    code: 'DEVOPS301',
    name: 'DevOps & CI/CD',
    description: 'Docker, Kubernetes, Jenkins và automation trong phát triển phần mềm.',
    instructor: 'TS. Lý Văn M',
    instructorAvatar: '/user.jpg',
    department: 'Khoa Công nghệ Phần mềm',
    semester: 'HK1 2024-2025',
    credits: 4,
    schedule: 'Thứ 2, 4 (13:00 - 15:30)',
    students: 19,
    maxStudents: 25,
    rating: 4.7,
    reviews: 43,
    level: 'Advanced',
    tags: ['DevOps', 'Docker', 'Kubernetes', 'CI/CD'],
    enrolled: false,
  },
];